site_name: dcrdocs
theme: slate
site_url: https://docs.decred.org
repo_url: https://github.com/decred/dcrdocs
markdown_extensions:
  - footnotes
  - smarty
  - mdx_math
  - toc:
      permalink: True
  - tables
extra_javascript:
    - http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
extra_css:
    - https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css
    - css/style.css
pages:
- Home: 'index.md'
- Getting Started:
  - 'Overview': 'getting-started/overview.md'
  - User Guides:
    - 'Windows': 'getting-started/user-guides/windows.md'
    - 'Linux': 'getting-started/user-guides/linux.md'
    - 'Web': 'getting-started/user-guides/web.md'
  - 'Obtaining DCR': 'getting-started/obtaining-dcr.md'
  - 'Using the Block Explorer': 'getting-started/using-the-block-explorer.md'
- Mining:
  - 'Overview': 'mining/overview.md'
  - Proof-of-work:
    - Pool Mining:
      - cgminer:
        - 'Windows': 'mining/proof-of-work/pool-mining/cgminer/windows.md'
        - 'Linux': 'mining/proof-of-work/pool-mining/cgminer/linux.md'
    - Solo Mining:
      - cgminer:
        - 'Windows': 'mining/proof-of-work/solo-mining/cgminer/windows.md'
        - 'Linux': 'mining/proof-of-work/solo-mining/cgminer/linux.md'
  - Proof-of-stake:
    - 'Pool Mining': 'mining/proof-of-stake/pool-mining.md'
    - 'Solo Mining': 'mining/proof-of-stake/solo-mining.md'
- FAQ:
  - 'Overview': 'faq/overview.md'
  - 'General': 'faq/general.md'
  - 'Configuration': 'faq/configuration.md'
  - 'Wallets and Seeds': 'faq/wallets-and-seeds.md'
  - 'Web Client': 'faq/web-client.md'
  - 'Blocks': 'faq/blocks.md'
  - Proof-of-stake:
    - 'Solo Mining': 'faq/proof-of-stake/solo-mining.md'
    - 'Buying Tickets and Fees': 'faq/proof-of-stake/buying-tickets-and-fees.md'
    - 'Voting Tickets': 'faq/proof-of-stake/voting-tickets.md'
    - 'Stake Pools': 'faq/proof-of-stake/stake-pools.md'
  - 'Proof-of-work Mining': 'faq/proof-of-work-mining.md'
- Advanced:
  - 'Storing Login Details': 'advanced/storing-login-details.md'
  - 'Network Parameters': 'advanced/network-parameters.md'
  - 'Block Header Specifications': 'advanced/block-header-specifications.md'
  - 'Verifying Binaries': 'advanced/verifying-binaries.md'
- Research:
  - 'Overview': 'research/overview.md'
  - 'Hybrid Design': 'research/hybrid-design.md'
  - 'Decentralized Stake Pooling': 'research/decentralized-stake-pooling.md'
  - 'Elliptic Curve Signature Algorithms': 'research/elliptic-curve-signature-algorithms.md'
  - 'BLAKE-256 Hash Function': 'research/blake-256-hash-function.md'
  - 'Script Extensions': 'research/script-extensions.md'
  - 'Signature Script Isolation and Fraud Proofs': 'research/signature-script-isolation-and-fraud-proofs.md'
  - 'Transaction Extensions': 'research/transaction-extensions.md'
  - 'Schnorr Signatures': 'research/schnorr-signatures.md'
  - 'Miscellaneous Improvements': 'research/miscellaneous-improvements.md'
- About:
  - 'Credits': 'about/credits.md'
  - 'License': 'about/license.md'
copyright: dcrdocs v0.0.1. Decred Project 2016.